<a href="https://colab.research.google.com/github/basangoudapatil/Task-6/blob/main/boston_assignment4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

In [14]:
phi = np.loadtxt('/content/train.csv', delimiter=',', dtype='float', skiprows=1, usecols=tuple(range(1,14)))
display(phi[0:5])

array([[9.55770e-01, 0.00000e+00, 8.14000e+00, 0.00000e+00, 5.38000e-01,
        6.04700e+00, 8.88000e+01, 4.45340e+00, 4.00000e+00, 3.07000e+02,
        2.10000e+01, 3.06380e+02, 1.72800e+01],
       [2.87500e-02, 2.80000e+01, 1.50400e+01, 0.00000e+00, 4.64000e-01,
        6.21100e+00, 2.89000e+01, 3.66590e+00, 4.00000e+00, 2.70000e+02,
        1.82000e+01, 3.96330e+02, 6.21000e+00],
       [1.22358e+00, 0.00000e+00, 1.95800e+01, 0.00000e+00, 6.05000e-01,
        6.94300e+00, 9.74000e+01, 1.87730e+00, 5.00000e+00, 4.03000e+02,
        1.47000e+01, 3.63430e+02, 4.59000e+00],
       [5.66637e+00, 0.00000e+00, 1.81000e+01, 0.00000e+00, 7.40000e-01,
        6.21900e+00, 1.00000e+02, 2.00480e+00, 2.40000e+01, 6.66000e+02,
        2.02000e+01, 3.95690e+02, 1.65900e+01],
       [4.54400e-02, 0.00000e+00, 3.24000e+00, 0.00000e+00, 4.60000e-01,
        6.14400e+00, 3.22000e+01, 5.87360e+00, 4.00000e+00, 4.30000e+02,
        1.69000e+01, 3.68570e+02, 9.09000e+00]])

In [15]:
phi_test = np.loadtxt('/content/test.csv', delimiter=',', dtype='float', skiprows=1, usecols=tuple(range(1,14)))
display(phi_test[0:5])

array([[1.06120e-01, 3.00000e+01, 4.93000e+00, 0.00000e+00, 4.28000e-01,
        6.09500e+00, 6.51000e+01, 6.33610e+00, 6.00000e+00, 3.00000e+02,
        1.66000e+01, 3.94620e+02, 1.24000e+01],
       [3.41090e-01, 0.00000e+00, 7.38000e+00, 0.00000e+00, 4.93000e-01,
        6.41500e+00, 4.01000e+01, 4.72110e+00, 5.00000e+00, 2.87000e+02,
        1.96000e+01, 3.96900e+02, 6.12000e+00],
       [1.22472e+01, 0.00000e+00, 1.81000e+01, 0.00000e+00, 5.84000e-01,
        5.83700e+00, 5.97000e+01, 1.99760e+00, 2.40000e+01, 6.66000e+02,
        2.02000e+01, 2.46500e+01, 1.56900e+01],
       [2.24890e-01, 1.25000e+01, 7.87000e+00, 0.00000e+00, 5.24000e-01,
        6.37700e+00, 9.43000e+01, 6.34670e+00, 5.00000e+00, 3.11000e+02,
        1.52000e+01, 3.92520e+02, 2.04500e+01],
       [1.80028e+00, 0.00000e+00, 1.95800e+01, 0.00000e+00, 6.05000e-01,
        5.87700e+00, 7.92000e+01, 2.42590e+00, 5.00000e+00, 4.03000e+02,
        1.47000e+01, 2.27610e+02, 1.21400e+01]])

In [16]:
y = np.loadtxt('/content/train.csv', dtype='float', delimiter=',', skiprows=1, usecols=14, ndmin=2)
display(y[0:5])

array([[14.8],
       [25. ],
       [41.3],
       [18.4],
       [19.8]])

In [17]:
phi.shape, phi_test.shape

((400, 13), (105, 13))

In [18]:
phi_test = np.concatenate((phi_test, np.ones((105, 1))), axis=1)
phi = np.concatenate((phi, np.ones((400, 1))), axis=1)

In [19]:
display(phi[0:5])
display(phi_test[0])

array([[9.55770e-01, 0.00000e+00, 8.14000e+00, 0.00000e+00, 5.38000e-01,
        6.04700e+00, 8.88000e+01, 4.45340e+00, 4.00000e+00, 3.07000e+02,
        2.10000e+01, 3.06380e+02, 1.72800e+01, 1.00000e+00],
       [2.87500e-02, 2.80000e+01, 1.50400e+01, 0.00000e+00, 4.64000e-01,
        6.21100e+00, 2.89000e+01, 3.66590e+00, 4.00000e+00, 2.70000e+02,
        1.82000e+01, 3.96330e+02, 6.21000e+00, 1.00000e+00],
       [1.22358e+00, 0.00000e+00, 1.95800e+01, 0.00000e+00, 6.05000e-01,
        6.94300e+00, 9.74000e+01, 1.87730e+00, 5.00000e+00, 4.03000e+02,
        1.47000e+01, 3.63430e+02, 4.59000e+00, 1.00000e+00],
       [5.66637e+00, 0.00000e+00, 1.81000e+01, 0.00000e+00, 7.40000e-01,
        6.21900e+00, 1.00000e+02, 2.00480e+00, 2.40000e+01, 6.66000e+02,
        2.02000e+01, 3.95690e+02, 1.65900e+01, 1.00000e+00],
       [4.54400e-02, 0.00000e+00, 3.24000e+00, 0.00000e+00, 4.60000e-01,
        6.14400e+00, 3.22000e+01, 5.87360e+00, 4.00000e+00, 4.30000e+02,
        1.69000e+01, 3.685

array([1.0612e-01, 3.0000e+01, 4.9300e+00, 0.0000e+00, 4.2800e-01,
       6.0950e+00, 6.5100e+01, 6.3361e+00, 6.0000e+00, 3.0000e+02,
       1.6600e+01, 3.9462e+02, 1.2400e+01, 1.0000e+00])

In [20]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

phi = scaler.fit_transform(phi)
phi_test = scaler.transform(phi_test)

In [21]:
display(phi[0:3])

array([[1.06411199e-02, 0.00000000e+00, 2.81524927e-01, 0.00000000e+00,
        3.14814815e-01, 4.11245153e-01, 8.84654995e-01, 3.02248816e-01,
        1.30434783e-01, 2.29007634e-01, 8.93617021e-01, 7.71748449e-01,
        4.26074896e-01, 0.00000000e+00],
       [2.21317669e-04, 2.94736842e-01, 5.34457478e-01, 0.00000000e+00,
        1.62551440e-01, 4.46574752e-01, 2.67765191e-01, 2.30637725e-01,
        1.30434783e-01, 1.58396947e-01, 5.95744681e-01, 9.98562711e-01,
        1.19001387e-01, 0.00000000e+00],
       [1.36513324e-02, 0.00000000e+00, 7.00879765e-01, 0.00000000e+00,
        4.52674897e-01, 6.04265403e-01, 9.73223481e-01, 6.79918886e-02,
        1.73913043e-01, 4.12213740e-01, 2.23404255e-01, 9.15603409e-01,
        7.40638003e-02, 0.00000000e+00]])

In [22]:
display(phi_test[0:2])

array([[0.00109096, 0.31578947, 0.1638563 , 0.        , 0.08847737,
        0.42158552, 0.64057673, 0.47345161, 0.2173913 , 0.21564885,
        0.42553191, 0.99425084, 0.29070735, 0.        ],
       [0.00373205, 0.        , 0.25366569, 0.        , 0.22222222,
        0.49052133, 0.3831102 , 0.32659204, 0.17391304, 0.19083969,
        0.74468085, 1.        , 0.11650485, 0.        ]])

In [23]:
y_log = np.log(y)
display(y_log[0:2])

array([[2.69462718],
       [3.21887582]])

In [24]:
def error_f(p, phi, w):
  if p==2:
    errorf = (2 * (np.dot(np.dot(np.transpose(phi), phi), w) - np.dot(np.transpose(phi),y)) + lambd * p * np.power(np.absolute(w),(p-1)))
  if p < 2 and p > 1:
    errorf = (2 * (np.dot(np.dot(np.transpose(phi), phi),w) - np.dot(np.transpose(phi), y))+ lambd * p * np.power(np.absolute(w), (p-1)) * np.sign(w))
  return errorf

In [25]:
# Dictionary containing filenames as keys and p as values
filenames = {
             'result_p1.csv': 1.75,
             'result_p2.csv': 1.5,
             'result_p3.csv': 1.3
             }

# For each item in this dictionary
for (fname, p) in filenames.items():
    # Set initial w to zeros
    w = np.zeros((14, 1))

    # Hyperparameter lambda value
    lambd = 0.2

    # Maximum step size
    t = 0.00012

    # Calculate new value of w
    w_new = w - t * error_f(p, phi, w)

    i = 0
    # Repeat steps until error between consecutive w is less than threshold
    while(np.linalg.norm(w_new-w) > 10 ** -10):
        w = w_new
        w_new = w - t * error_f(p, phi, w)
        i = i + 1

    # Load values of id
    id_test = np.loadtxt('/content/test.csv', dtype='int', delimiter=',',
                         skiprows=1, usecols=0, ndmin=2)

    # Calculate y for test data
    y_test = np.exp(np.dot(phi_test, w_new))

    # Save the ids and y
    np.savetxt(fname, np.concatenate((id_test, y_test), axis=1),
               delimiter=',', fmt=['%d', '%f'], header='ID,MEDV')